### ISSUE TITLE
Tested latest you made for multiple classes. One folder is missing.

### ISSUE THREAD

**Issue by chroots** [mrbuds/EZDownRank#1]
Howdy, I tested last night raid with your latest recent you made for multiple healing classes and I tried it and turn it out you missed the LibFrame-1.0 folder so i had to add LibFrame-1.0 and tested on my holy priest, restoration druid and holy pally. it working beautifully!

Keep it up!!!

**Comment by mrbuds** [comment]
These are included in release package https://github.com/mrbuds/EZDownRank/releases, or you can find package for alpha on curseforge at https://www.curseforge.com/wow/addons/ezdownrank/files
