### ISSUE TITLE
Buds is lazy

### ISSUE THREAD

**Issue by Translitdk** [mrbuds/EZDownRank#5]
-make it disappear on dead units
-i want circle shaped textures also
-would be nice to play tetris/snake on raid frames with this, while raid is afk

**Comment by mrbuds** [comment]
> -make it disappear on dead units

ok
> -i want circle shaped textures also

no
> -would be nice to play tetris/snake on raid frames with this, while raid is afk

no

**Comment by mrbuds** [comment]
fixed
